site_name: Research Notes
site_url: https://tom-mcmillan.github.io/research/
repo_url: https://github.com/tom-mcmillan/research
repo_name: research

theme:
  name: material
  palette:
    scheme: default
    primary: "#000000"
  features:
    - navigation.expand
    - navigation.instant
    - toc.following
    - search.highlight
    - search.suggest
    - content.code.copy


plugins:
  - search
  - awesome-nav
  - mermaid2
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      title: "Table of Contents"
      toc_depth: "2-3"
  - pymdownx.superfences
  - pymdownx.highlight

extra_css:
  - css/custom.css
