site_name: Research
site_url: https://tom-mcmillan.github.io/research/
repo_url: https://github.com/tom-mcmillan/research
repo_name: research

theme:
  name: material
  palette:
    scheme: default
    primary: "#000000"
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy

extra_css:
  - css/custom.css

plugins:
  - search
  - awesome-nav
  - mermaid2
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
