site_name: Research Notes
site_url: https://tom-mcmillan.github.io/research/
repo_url: https://github.com/tom-mcmillan/research
repo_name: research

theme:
  name: material
  palette:
    scheme: default         # keeps the light/dark toggle
    primary: blue
    accent: blue

plugins:
  - search
  - gen-nav
  - mermaid2
markdown_extensions:
  - admonition
  - toc:
      permalink: true
