nav:
  - Intro: index.md
  - Knowledge Protocol: knowledge-protocol.md
  - Intersubjective Computing: intersubjective-computing.md
  - Sail MCP: sail-mcp
  - Climate Index: climate-index
  - Vingworld: vingworld