name: Deploy docs

# Deploy the MkDocs site to GitHub Pages on every push to main
on:
  push:
    branches:
      - main

permissions:
  contents: write  # allow pushing to gh-pages branch

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy docs to GitHub Pages
        run: mkdocs gh-deploy --clean